# Generated by Django 2.2.5 on 2022-02-08 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writings', '0002_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='writing',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
